modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Zombie%20Proof%20Doors"
logoFile="icon.png"

[[mods]]
modId="zombieproofdoors"
version="3.3"
displayName="Zombie Proof Doors"
displayURL="https://serilum.com/mod/zombie-proof-doors"
authors="Rick South"
description='''Prevents zombies from targeting and breaking down doors.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jack, Jeremy Langford, Michael W. S., pepe1191, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.zombieproofdoors]]
    modId="collective"
    mandatory=true
    versionRange="[7.54,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.zombieproofdoors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.6]"
    ordering="NONE"
    side="BOTH"
