modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Zombie%20Proof%20Doors"
logoFile="icon.png"

[[mods]]
modId="zombieproofdoors"
version="3.4"
displayName="Zombie Proof Doors"
displayURL="https://serilum.com/mod/zombie-proof-doors"
authors="Rick South"
description='''Prevents zombies from targeting and breaking down doors.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, kate1073, Michael W. S., Tyler Behl, XAgent   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.zombieproofdoors]]
    modId="collective"
    type="required"
    versionRange="[7.84,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.zombieproofdoors]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.2,1.21.3]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "zombieproofdoors.mixins.json"